<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductCategory extends Seeder
{
    public function run()
    {
        $data = [
            [
                'prod_cat_id' => 1,
                'parent_id' => null,
                'category_name' => 'Watches',
                'description' => 'dfgdg dfgdf gdfg ',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '12',
                'image' => 'category_1684648999_9c73ff90c4abf9eee75a.jpg',
                'header_menu' => '1',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-03-25 14:42:52',
                'createdBy' => '1',
                'updatedDtm' => '2023-05-21 12:03:19',
                'updatedBy' => '1',
            ],
            [
                'prod_cat_id' => 2,
                'parent_id' => '1',
                'category_name' => 'Men\'s Watch',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '3',
                'image' => '',
                'header_menu' => '1',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-03-25 14:43:13',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-08 10:44:49',
                'updatedBy' => '1',
            ],
            [
                'prod_cat_id' => 3,
                'parent_id' => '1',
                'category_name' => 'Sport',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '17',
                'image' => '',
                'header_menu' => '0',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-03-30 11:54:39',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-04 12:35:57',
                'updatedBy' => '1',
            ],
            [
                'prod_cat_id' => 4,
                'parent_id' => null,
                'category_name' => 'Gadget',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '16',
                'image' => '',
                'header_menu' => '1',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-04-03 09:01:39',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-08 10:44:30',
                'updatedBy' => '1',
            ],
            [
                'prod_cat_id' => 5,
                'parent_id' => null,
                'category_name' => 'Gift Item',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '17',
                'image' => '',
                'header_menu' => '0',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-04-03 09:02:07',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-04 12:23:15',
                'updatedBy' => '1',
            ],
            [
                'prod_cat_id' => 6,
                'parent_id' => null,
                'category_name' => 'Toys',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '18',
                'image' => '',
                'header_menu' => '0',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-04-03 09:02:40',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-04 12:23:30',
                'updatedBy' => '1',
            ],
            [
                'prod_cat_id' => 7,
                'parent_id' => null,
                'category_name' => 'Popular',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '5',
                'image' => '',
                'header_menu' => '0',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-04-03 09:03:00',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-04 12:23:33',
                'updatedBy' => '1',
            ],
            [
                'prod_cat_id' => 8,
                'parent_id' => null,
                'category_name' => 'Gadgeteer',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '6',
                'image' => '',
                'header_menu' => '0',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-04-03 09:03:23',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-04 12:23:36',
                'updatedBy' => '1',
            ],
            [
                'prod_cat_id' => 9,
                'parent_id' => null,
                'category_name' => 'Gadget lover',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '13',
                'image' => '',
                'header_menu' => '0',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-04-03 09:24:53',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-04 12:23:40',
                'updatedBy' => '1',
            ],
            [
                'prod_cat_id' => 10,
                'parent_id' => null,
                'category_name' => 'Accessories',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '3',
                'image' => '',
                'header_menu' => '0',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-04-03 09:25:46',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-04 12:23:43',
                'updatedBy' => '1',
            ],
            [
                'prod_cat_id' => 11,
                'parent_id' => '10',
                'category_name' => 'kids',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '',
                'image' => '',
                'header_menu' => '0',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-04-03 09:26:48',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-03 09:26:48',
                'updatedBy' => '',
            ],
            [
                'prod_cat_id' => 12,
                'parent_id' => '10',
                'category_name' => 'Gift Hampers',
                'description' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'icon_id' => '3',
                'image' => '',
                'header_menu' => '0',
                'sort_order' => '0',
                'status' => '1',
                'createdDtm' => '2023-04-13 12:02:39',
                'createdBy' => '1',
                'updatedDtm' => '2023-04-13 12:02:39',
                'updatedBy' => '',
            ],
        ];
        // Using Query Builder
        $this->db->table('cc_product_category')->insertBatch($data);
    }
}
