<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Products extends Seeder
{
    public function run()
    {
        $data = [
            [
                'product_id' => 1,
                'store_id' => '1',
                'name' => 'Samsung Galaxy Watch5 Bluetooth (40mm) - Silver ',
                'model' => 'R900',
                'product_code' => '',
                'image' => 'pro_1685165596_419e5dd034e3a63d331d.jpg',
                'brand_id' => '5',
                'sort_order' => '0',
                'price' => '600.00',
                'quantity' => '7',
                'product_category_id' => '',
                'featured' => '1',
                'average_feedback' => '',
                'date_available' => '',
                'weight' => '0.0000',
                'length' => '0.0000',
                'width' => '0.0000',
                'height' => '0.0000',
                'sort_order' => '0',
                'status' => 'Active',
                'createdDtm' => '2023-05-27 11:33:16',
                'createdBy' => '1',
                'updatedBy' => '',
                'updatedDtm' => '2023-05-27 18:21:45',
            ],
            [
                'product_id' => 2,
                'store_id' => '1',
                'name' => 'Samsung Galaxy Watch5',
                'model' => 'R900',
                'product_code' => '',
                'image' => 'pro_1685165844_7d4fe81fee1ab5cd4cb2.jpg',
                'brand_id' => '5',
                'sort_order' => '0',
                'price' => '1500.00',
                'quantity' => '9',
                'product_category_id' => '',
                'featured' => '1',
                'average_feedback' => '5',
                'date_available' => '',
                'weight' => '0.0000',
                'length' => '0.0000',
                'width' => '0.0000',
                'height' => '0.0000',
                'sort_order' => '0',
                'status' => 'Active',
                'createdDtm' => '2023-05-27 11:37:24',
                'createdBy' => '1',
                'updatedBy' => '',
                'updatedDtm' => '2023-05-27 18:21:45',
            ],
            [
                'product_id' => 3,
                'store_id' => '1',
                'name' => 'Samsung Galaxy Watch5 - Pink Gold',
                'model' => 'R900',
                'product_code' => '',
                'image' => 'pro_1685166111_3851b536ef8636df4061.jpg',
                'brand_id' => '5',
                'sort_order' => '0',
                'price' => '1800.00',
                'quantity' => '9',
                'product_category_id' => '',
                'featured' => '1',
                'average_feedback' => '',
                'date_available' => '',
                'weight' => '0.0000',
                'length' => '0.0000',
                'width' => '0.0000',
                'height' => '0.0000',
                'sort_order' => '0',
                'status' => 'Active',
                'createdDtm' => '2023-05-27 11:41:51',
                'createdBy' => '1',
                'updatedBy' => '',
                'updatedDtm' => '2023-05-27 16:17:36',
            ],
            [
                'product_id' => 4,
                'store_id' => '1',
                'name' => 'Apple Watch SE 2 GPS 40mm Silver Aluminium with ',
                'model' => 'MNT93',
                'product_code' => '',
                'image' => 'pro_1685166347_60e9df25486d7075424a.jpg',
                'brand_id' => '6',
                'sort_order' => '0',
                'price' => '3500.00',
                'quantity' => '9',
                'product_category_id' => '',
                'featured' => '1',
                'average_feedback' => '',
                'date_available' => '',
                'weight' => '0.0000',
                'length' => '0.0000',
                'width' => '0.0000',
                'height' => '0.0000',
                'sort_order' => '0',
                'status' => 'Active',
                'createdDtm' => '2023-05-27 11:45:47',
                'createdBy' => '1',
                'updatedBy' => '',
                'updatedDtm' => '2023-05-27 18:21:45',
            ],
            [
                'product_id' => 5,
                'store_id' => '1',
                'name' => 'Apple Watch 8 GPS 41mm Midnight Aluminium ',
                'model' => 'MNU73',
                'product_code' => '',
                'image' => 'pro_1685166616_5a0898e6f1d378bdab46.jpg',
                'brand_id' => '6',
                'sort_order' => '0',
                'price' => '2400.00',
                'quantity' => '10',
                'product_category_id' => '',
                'featured' => '1',
                'average_feedback' => '',
                'date_available' => '',
                'weight' => '0.0000',
                'length' => '0.0000',
                'width' => '0.0000',
                'height' => '0.0000',
                'sort_order' => '0',
                'status' => 'Active',
                'createdDtm' => '2023-05-27 11:50:16',
                'createdBy' => '1',
                'updatedBy' => '',
                'updatedDtm' => '2023-05-27 11:50:16',
            ],
            [
                'product_id' => 6,
                'store_id' => '1',
                'name' => 'Xiaomi Mi Band 7 Smart Wristband Watch',
                'model' => 'Watch',
                'product_code' => '',
                'image' => 'pro_1685166817_8c472b56d781d2f24910.jpg',
                'brand_id' => '5',
                'sort_order' => '0',
                'price' => '600.00',
                'quantity' => '10',
                'product_category_id' => '',
                'featured' => '1',
                'average_feedback' => '',
                'date_available' => '',
                'weight' => '0.0000',
                'length' => '0.0000',
                'width' => '0.0000',
                'height' => '0.0000',
                'sort_order' => '0',
                'status' => 'Active',
                'createdDtm' => '2023-05-27 11:53:37',
                'createdBy' => '1',
                'updatedBy' => '',
                'updatedDtm' => '2023-05-27 11:53:38',
            ],
            [
                'product_id' => 7,
                'store_id' => '1',
                'name' => 'Black Bay Fifty Eight Automatic Chronometer Blue Dial Men\'s Watch',
                'model' => 'M79030B-0001',
                'product_code' => '',
                'image' => 'pro_1685282344_0da665be1f5f01b08642.jpg',
                'brand_id' => '5',
                'sort_order' => '0',
                'price' => '3350.00',
                'quantity' => '100',
                'product_category_id' => '',
                'featured' => '0',
                'average_feedback' => '',
                'date_available' => '',
                'weight' => '4.0000',
                'length' => '20.0000',
                'width' => '20.0000',
                'height' => '20.0000',
                'sort_order' => '0',
                'status' => 'Active',
                'createdDtm' => '2023-05-28 19:59:04',
                'createdBy' => '1',
                'updatedBy' => '',
                'updatedDtm' => '2023-05-28 19:59:05',
            ],
        ];

        // Using Query Builder
        $this->db->table('cc_products')->insertBatch($data);
    }
}
